using System;

namespace Quicksicle.Enums
{
    public enum WorldPacketId
    {
        MSG_WORLD_LOGIN_SESSION_NOTIFY,
        MSG_WORLD_CLIENT_VALIDATION,
        MSG_WORLD_CLIENT_CHARACTER_LIST_REQUEST,
        MSG_WORLD_CLIENT_CHARACTER_CREATE_REQUEST,
        MSG_WORLD_CLIENT_LOGIN_REQUEST,
        MSG_WORLD_CLIENT_GAME_MSG,
        MSG_WORLD_CLIENT_CHARACTER_DELETE_REQUEST,
        MSG_WORLD_CLIENT_CHARACTER_RENAME_REQUEST,
        MSG_WORLD_CLIENT_HAPPY_FLOWER_MODE_NOTIFY,
        MSG_WORLD_CLIENT_SLASH_RELOAD_MAP,
        MSG_WORLD_CLIENT_SLASH_PUSH_MAP_REQUEST,
        MSG_WORLD_CLIENT_SLASH_PUSH_MAP,
        MSG_WORLD_CLIENT_SLASH_PULL_MAP,
        MSG_WORLD_CLIENT_LOCK_MAP_REQUEST,
        MSG_WORLD_CLIENT_GENERAL_CHAT_MESSAGE,
        MSG_WORLD_CLIENT_HTTP_MONITOR_INFO_REQUEST,
        MSG_WORLD_CLIENT_SLASH_DEBUG_SCRIPTS,
        MSG_WORLD_CLIENT_MODELS_CLEAR,
        MSG_WORLD_CLIENT_EXHIBIT_INSERT_MODEL,
        MSG_WORLD_CLIENT_LEVEL_LOAD_COMPLETE,
        MSG_WORLD_CLIENT_TMP_GUILD_CREATE,
        MSG_WORLD_CLIENT_ROUTE_PACKET,
        MSG_WORLD_CLIENT_POSITION_UPDATE,
        MSG_WORLD_CLIENT_MAIL,
        MSG_WORLD_CLIENT_WORD_CHECK,
        MSG_WORLD_CLIENT_STRING_CHECK,
        MSG_WORLD_CLIENT_GET_PLAYERS_IN_ZONE,
        MSG_WORLD_CLIENT_REQUEST_UGC_MANIFEST_INFO,
        MSG_WORLD_CLIENT_BLUEPRINT_GET_ALL_DATA_REQUEST,
        MSG_WORLD_CLIENT_CANCEL_MAP_QUEUE,
        MSG_WORLD_CLIENT_HANDLE_FUNNESS,
        MSG_WORLD_CLIENT_FAKE_PRG_CSR_MESSAGE,
        MSG_WORLD_CLIENT_REQUEST_FREE_TRIAL_REFRESH,
        MSG_WORLD_CLIENT_GM_SET_FREE_TRIAL_STATUS,
        MSG_WORLD_CLIENT_GET_LAPSED_MEMBERSHIP_STATUS
    }
}
